name: Dev Build

on:
    pull_request:
        branches: ['**']
    push:
        branches: [develop]

jobs:
    test:
        if: false
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
            - name: Cache NPM dependencies
              uses: actions/setup-node@v4
              with:
                  node-version: 21
                  cache: 'npm'
            - name: Install NPM dependencies
              run: npm ci
            - name: Compile typescript
              run: npm run build
            - name: Execute test suites
              run: npm test
              env:
                  NODE_ENV: test
                  PORT: 3000
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
            - name: Cache NPM dependencies
              uses: actions/setup-node@v4
              with:
                  node-version: 21
                  cache: 'npm'
            - name: Install NPM dependencies
              run: npm ci
            - name: Lint and check formatting
              run: npm run lint

    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
            - name: Cache NPM dependencies
              uses: actions/setup-node@v4
              with:
                  node-version: 21
                  cache: 'npm'
            - name: Install NPM dependencies
              run: npm ci
            - name: Build project
              run: npm run build
